package fuzz

import (
	"fmt"
	"strings"
)

const QuarryFuzzImage = "quarry-fuzz:latest"

const defaultInstrumentedTag = "quarry-instrumented:latest"

// keep in sync with defaultHarness, the argv the Campaign feeds
const defaultHarnessOut = "/harness"

// -fsanitize=fuzzer links AFL++'s driver, supplying main for an LLVMFuzzerTestOneInput harness
var baseHarnessCFlags = []string{"-fsanitize=fuzzer", "-fno-omit-frame-pointer", "-g", "-O1"}

// Dockerfile() and BuildArgs() are pure functions of the spec.
type BuildSpec struct {
	BaseImage string

	// host path to the target source tree; it becomes the docker build CONTEXT
	SourceDir string

	BuildCommand []string

	// harness translation unit, relative to SourceDir
	HarnessSource string

	// a .cpp/.cc harness must compile AND link as C++ for its std:: symbols to resolve
	HarnessCxx bool

	// build-time deps: pre-COPY layer, may reach the network; the fuzz RUN stays air-gapped
	AptPackages []string

	HarnessOut string

	LinkArtifacts []string // in-image; order is preserved (link order matters)

	IncludeDirs []string
	ExtraCFlags []string
	LinkLibs    []string

	// afl-clang-lto: a cleaner coverage map, but the target must link under LTO
	LTO bool

	// in-image path of an additional CMPLOG/RedQueen build for afl-fuzz -c
	CmplogOut string
	// empty ⇒ CMPLOG on the harness TU only, not on the linked libraries
	CmplogBuildCommand []string

	ImageTag string
}

func (s BuildSpec) Compiler() string {
	if s.LTO {
		return "afl-clang-lto"
	}
	return "afl-clang-fast"
}

// HarnessCompiler is the compiler for the FINAL harness compile/link only.
func (s BuildSpec) HarnessCompiler() string {
	if s.HarnessCxx {
		return s.Compiler() + "++"
	}
	return s.Compiler()
}

func (s BuildSpec) baseImage() string {
	if s.BaseImage != "" {
		return s.BaseImage
	}
	return QuarryFuzzImage
}

func (s BuildSpec) harnessOut() string {
	if s.HarnessOut != "" {
		return s.HarnessOut
	}
	return defaultHarnessOut
}

func (s BuildSpec) imageTag() string {
	if s.ImageTag != "" {
		return s.ImageTag
	}
	return defaultInstrumentedTag
}

func (s BuildSpec) harnessCompile(out string, cmplog bool) string {
	var parts []string
	if cmplog {
		parts = append(parts, "AFL_LLVM_CMPLOG=1")
	}
	parts = append(parts, s.HarnessCompiler())
	parts = append(parts, baseHarnessCFlags...)
	parts = append(parts, s.ExtraCFlags...)
	for _, d := range s.IncludeDirs {
		parts = append(parts, "-I", d)
	}
	parts = append(parts, s.HarnessSource)
	parts = append(parts, s.LinkArtifacts...)
	parts = append(parts, s.LinkLibs...)
	parts = append(parts, "-o", out)
	return strings.Join(parts, " ")
}

// a spec must produce SOMETHING instrumented, or the campaign fuzzes a baked binary
func (s BuildSpec) Validate() error {
	if s.HarnessSource == "" && len(s.BuildCommand) == 0 {
		return fmt.Errorf("fuzz: BuildSpec needs a HarnessSource to compile or a BuildCommand that emits the harness")
	}
	if s.CmplogOut != "" && s.HarnessSource == "" && len(s.CmplogBuildCommand) == 0 {
		return fmt.Errorf("fuzz: BuildSpec.CmplogOut needs a HarnessSource to recompile or a CmplogBuildCommand that emits the CMPLOG harness")
	}
	return nil
}

func (s BuildSpec) Dockerfile() (string, error) {
	if err := s.Validate(); err != nil {
		return "", err
	}
	cc := s.Compiler()
	var b strings.Builder
	b.WriteString("# Generated by quarry (BuildSpec.Dockerfile).\n")
	fmt.Fprintf(&b, "FROM %s\n\n", s.baseImage())
	b.WriteString("ENV AFL_USE_ASAN=1\n")
	fmt.Fprintf(&b, "ENV CC=%s CXX=%s++\n", cc, cc)
	// AFL_QUIET: the per-compile banner corrupts autoconf feature tests
	b.WriteString("ENV AFL_SKIP_CPUFREQ=1 AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1 AFL_QUIET=1\n\n")

	if len(s.AptPackages) > 0 {
		fmt.Fprintf(&b, "RUN apt-get update && apt-get install -y --no-install-recommends %s && rm -rf /var/lib/apt/lists/*\n\n",
			strings.Join(s.AptPackages, " "))
	}

	b.WriteString("WORKDIR /src\n")
	b.WriteString("COPY . /src\n\n")

	for _, cmd := range s.BuildCommand {
		cmd = strings.TrimSpace(cmd)
		if cmd == "" {
			continue
		}
		fmt.Fprintf(&b, "RUN %s\n", cmd)
	}

	if s.HarnessSource != "" {
		b.WriteString("\n# Harness compile against the instrumented build (coverage build).\n")
		fmt.Fprintf(&b, "RUN %s\n", s.harnessCompile(s.harnessOut(), false))
	}

	if s.CmplogOut != "" {
		b.WriteString("\n# CMPLOG/RedQueen input-to-state build for afl-fuzz -c.\n")
		for _, cmd := range s.CmplogBuildCommand {
			cmd = strings.TrimSpace(cmd)
			if cmd == "" {
				continue
			}
			fmt.Fprintf(&b, "RUN AFL_LLVM_CMPLOG=1 %s\n", cmd)
		}
		if s.HarnessSource != "" {
			fmt.Fprintf(&b, "RUN %s\n", s.harnessCompile(s.CmplogOut, true))
		}
	}
	return b.String(), nil
}

// the caller must first write Dockerfile()'s output to dockerfilePath, inside the context
func (s BuildSpec) BuildArgs(dockerfilePath string) ([]string, error) {
	if err := s.Validate(); err != nil {
		return nil, err
	}
	if s.SourceDir == "" {
		return nil, fmt.Errorf("fuzz: BuildSpec.SourceDir is required as the docker build context")
	}
	if dockerfilePath == "" {
		return nil, fmt.Errorf("fuzz: BuildArgs needs a path to write the generated Dockerfile to")
	}
	return []string{"build", "-t", s.imageTag(), "-f", dockerfilePath, s.SourceDir}, nil
}

// on the modern AFL++ engine; the caller still sets SeedDir, OutDir and DockerBin
func (s BuildSpec) InstrumentedCampaign() Campaign {
	c := Campaign{
		Image:       s.imageTag(),
		Engine:      EngineAFLPlusPlus,
		HarnessArgv: []string{s.harnessOut(), "@@"},
		MOpt:        true,
	}
	if s.CmplogOut != "" {
		c.CmplogBin = s.CmplogOut
	}
	return c
}
